version: '3.7'
services:
  charmander:
    image: charmander
    ports:
      - "8084:8080"
      - "8010:8000"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:8000,server=y,suspend=n"
  evee:
    image: eevee
    ports:
      - "80:8080"
      - "8011:8000"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:8000,server=y,suspend=n"